// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crdvvzncxicklblypvnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNyZHZ2em5jeGlja2xibHlwdm56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNTkzMDgsImV4cCI6MjA3MzkzNTMwOH0.xbfmC2RWGDDz1pcU38naYxIhFnuFLC6EGY1VRwPCbq4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});